language: c

compiler:
  - gcc
  - clang

# Make sure CMake is installed
install: |
  sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe"
  sudo apt-get install -y cmake doxygen python-sphinx gcc make check

# Run the Build script
script: |
  mkdir -p _build
  cd _build
  cmake ..
  make VERBOSE=1
  cd ..
  make test

# Run Tests
after_script:
 - if [ -f CTestTestfile.cmake ]; then ctest -V . ; fi

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#cherokee"
    use_notice: true
    skip_join: true
