language: c

matrix:
  include:
    - compiler: gcc
      env: BUILD=cmake
    - compiler: clang
      env: BUILD=cmake CMAKE_OPTION="-DUSE_VALGRIND=no" CFLAGS=-fsanitize=address
    - compiler: gcc
      env: BUILD=cmake CMAKE_OPTION="-DENABLE_GCOV=yes -DUSE_VALGRIND=no" COVERALLS=yes
    - compiler: gcc
      env: BUILD=cmake CMAKE_OPTION="-DENABLE_GCOV=no -DUSE_VALGRIND=yes"

before_install: |
  sudo apt-get update -qq

install: |
  sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe"
  sudo apt-get install -y cmake doxygen python-sphinx gcc make check valgrind
  sudo pip install cpp-coveralls --use-mirrors

# Run the Build script
script: |
  mkdir -p _build
  cd _build
  cmake $CMAKE_OPTION -DCMAKE_BUILD_TYPE:STRING=Debug ..
  make VERBOSE=1
  make docs
  make test ARGS="-V"
  cd ..

after_success: |
  if [ x$COVERALLS == xyes ]; then \
    coveralls --verbose --exclude doc --exclude test --exclude libchula/test --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h'; \
  fi

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#cherokee"
